name: "Publish Github Release"
description: "Publihs new release to GitHub releases"

inputs:
  github-token:
    description: "GitHub token secret"
    required: true
  tarball-file:
    description: "Dist tarball path"
    required: true
  prerelease:
    required: true
    description: "Is this a dev/prerelease?"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Pack and sign dist tarball
      shell: "bash"
      run: |
        yarn pack --filename ${{ inputs.tarball-file }}
        gpg --armor --detach-sign ${{ inputs.tarball-file }}

    - name: Create and publish GitHub release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ inputs.github-token }}
        prerelease: ${{ inputs.prerelease }}
        files: |
          ${{ inputs.tarball-file }}
          ${{ inputs.tarball-file }}.asc
          LICENSE
          README.md