name: Publish (Mainline Release)

on:
  push:
    tags:
      - "v[01].[0-9]+.[0-9]+"
      - "!v*-dev*"
      - "!v*-beta*"
      - "!v*-alpha*"

jobs:
  tagged_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/publish-setup
        id: publish_setup

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.BLEAKER_GPG_PRIVKEY }}
          passphrase:      ${{ secrets.BLEAKER_GPG_PASSPHRASE }}

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          scope: "@synapseprotocol"
          registry-url: "https://registry.npmjs.org"
          node-version-file: '.nvmrc'

      - uses: ./.github/actions/yarn-cache
        with:
          node-version: ${{ steps.publish_setup.outputs.nvm-version }}

      - run: yarn run build

      - name: Build dist tarball
        run: yarn pack --filename ${{ steps.publish_setup.outputs.tarball-file }}

      - name: GPG sign dist tarball
        run: gpg --armor --detach-sign ${{ steps.publish_setup.outputs.tarball-file }}

      - name: Create and publish GitHub release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            ${{ steps.publish_setup.outputs.tarball-file }}
            ${{ steps.publish_setup.outputs.tarball-file }}.asc
            LICENSE
            README.md

      - name: Publish to NPM
        run: yarn publish --non-interactive --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SERVICE_ACCOUNT_TOKEN }}