name: Yarn Cache

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version string"
        required: true
        type: string
      platform:
        description: "Platform"
        required: false
        type: string
        default: "ubuntu-latest"
    outputs:
      cache-hit:
        description: "Was cache hit?"
        value: ${{ jobs.yarn_cache.outputs.cache-hit }}

jobs:
  yarn_cache:
    runs-on: ${{ inputs.platform }}

    steps:
      - id: cache_dir
        run: echo ::set-output name=dir::$(yarn cache dir)

      - uses: actions/cache@v3
        id: yarn_cache
        with:
          path: ${{ steps.cache_dir.outputs.dir }}
          key: ${{ runner.os }}-${{ inputs.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.node-version }}-yarn-

      - run: yarn install
        if: steps.yarn_cache.outputs.cache-hit != 'true'

    outputs:
      cache-hit: ${{ steps.yarn_cache.cache-hit }}